version: "3.3"
services:
  spark-master:
    image: sense-net-spark:3.5.0
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_WORKLOAD=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080

  spark-worker:
    image: sense-net-spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=10
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker
    volumes:
      - /Users/layvvs/Desktop/Studying/BMSTU/Diploma/sense-net/data:/Users/layvvs/Desktop/Studying/BMSTU/Diploma/sense-net/data # needs in fix
    depends_on:
      - spark-master
